### PR TITLE
Updates to separate notebooks for figures by JDox pages

### PR DESCRIPTION
**Pull request by aliciacanipe**
## Description

Added notebooks to generate Figure 2 on NIRCam Sensitivities page, Figure 3 on NIRCam Bright Source Limits page, and Figure 5 on NIRCam Grism Time Series page. Also added a "data" directory to hold the text files that were sent to me to generate the figures. 

## How Has This Been Tested?

I ran the cells of the notebook to make sure everything works.

### CODE REVIEW

**Comment by aliciacanipe** [comment]
@bhilbert4  I started separating the notebooks by JDox page. I also added a directory for the data. The two old folders (scripts and notebooks) are there still, because I'm slowly separating the code out and it will take me a bit to get through all of it. Would you mind taking a look to make sure this is what you had in mind?

**Review by bhilbert4 — COMMENTED** [review]
It seems like it would be cleaner if data files lived in the same directories as the notebook they are associated with. Although if you have a data file that is used by multiple notebooks in different directories then it's not clear where the data file should go, so maybe a generic `data` directory is best.

Some of the notebooks look like they are under an `.ipynb_checkpoints` subdirectory (according to the Files Changed tab). Would be good to pull them out if that's really true.

I didn't open any of the notebooks, but the other thing I've learned about putting notebooks on github is that it's best if none of the cells in the notebooks are executed. Apparently if they are executed then github has trouble when it looks for changes from commit to commit, or something along those lines.

**Comment by aliciacanipe** [comment]
Yeah I was trying to figure out the best way to store the data. The same grism data is used for different pages. To avoid having to update the data in multiple locations I thought maybe one directory is best? Not sure about that though.

I also forgot to .gitignore the notebook checkpoints initially, so I need to delete those. The three notebooks I was actually trying to upload are there. Can I just trash those checkpoint commits?

**Comment by aliciacanipe** [comment]
Also meant to say I made sure to clear the outputs of the cells before adding them.

**Comment by bhilbert4** [comment]
You also have 2 files called `._saturation64.txt` and `saturation64.txt`. I'm assuming you only want the latter?

**Comment by aliciacanipe** [comment]
It's like I forgot how to use GitHub. I'll do better next time. I don't know why that file was there. I removed the checkpoints and the hidden file. Are you okay with a generic "data" directory for now? We may have to change it later, but right now the same data is used for different pages.

**Comment by bhilbert4** [comment]
Looks good to me. Keeping a generic data directory seems fine.

**Comment by aliciacanipe** [comment]
Sounds good. I'll keep working on it this way for now. Thanks!

**Pull request merged**
